server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://prod-db-server:3306/userdb_prod
    username: produser
    password: '{cipher}eb49571d77166466bcc870890542ba5c977438133d592cc25ae129d8dad2dd7c'

user-service:
  feature-flags:
    enable-registration: true
    enable-social-login: true

logging:
  level:
    com.example.userservice: INFO
