transaction:
  max:
    limit: 50000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '{cipher}67c7b999df2190d644e1d05455eecd8c4733d57c584a8f318921a67b3c0fa0b2'
  jpa:
    hibernate:
      ddl-auto: none
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
